# Generated by Django 4.2.14 on 2024-07-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_explorer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraphvector',
            name='paragraph_id',
        ),
        migrations.AddField(
            model_name='paragraphvector',
            name='chamber_type',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraphvector',
            name='source_file',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraphvector',
            name='transcript_type',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
