# Generated by Django 4.2.14 on 2024-07-19 14:55

from django.db import migrations
import pgvector.django.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('vector_explorer', '0002_remove_paragraphvector_paragraph_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paragraphvector',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='nhsw_index', opclasses=['vector_cosine_ops']),
        ),
    ]
