# Generated by Django 4.2.14 on 2024-09-06 15:03

from django.db import migrations, models
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('vector_explorer', '0003_paragraphvector_nhsw_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgramVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='ngram_nhsw_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
