# Generated by Django 4.2.14 on 2024-09-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vector_explorer', '0004_ngramvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngramvector',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
